projects:
  tiktokclone:
    schemaPath: 'D:/Antofatech/Proyectos/React_Native/vadim/TiktokClone/graphql/schema.json'
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
